// <auto-generated />
namespace Đồ_án_của_Thái.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddViewToChapter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddViewToChapter));
        
        string IMigrationMetadata.Id
        {
            get { return "202312110249111_AddViewToChapter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
